#ifndef SKARD_SKARD_H
#define SKARD_SKARD_H

#define SKARD_STR(x) #x
#define SKARD_XSTR(x) SKARD_STR(x)

#define SKARD_VERSION_MAJOR 0
#define SKARD_VERSION_MINOR 0
#define SKARD_VERSION_PATCH 1

#define SKARD_VERSION (SKARD_XSTR(SKARD_VERSION_MAJOR) "." SKARD_XSTR(SKARD_VERSION_MINOR) "." SKARD_XSTR(SKARD_VERSION_PATCH))


#endif //SKARD_SKARD_H
